import jsPDF from 'jspdf';

export const generateReportPDF = (report, interview, user) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text('InterviewAce AI', 20, 25);
  doc.setFontSize(12);
  doc.text('Interview Performance Report', 20, 33);

  y = 55;
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(14);
  doc.text(`Candidate: ${user?.name || 'N/A'}`, 20, y);
  y += 10;
  doc.setFontSize(11);
  doc.text(`Domain: ${interview?.domain || 'N/A'} | Difficulty: ${interview?.difficulty || 'N/A'}`, 20, y);
  y += 8;
  doc.text(`Date: ${new Date(interview?.completedAt || Date.now()).toLocaleDateString()}`, 20, y);
  y += 15;

  doc.setFontSize(18);
  doc.setTextColor(99, 102, 241);
  doc.text(`Overall Score: ${report.overallScore}%`, 20, y);
  y += 15;

  doc.setFontSize(12);
  doc.setTextColor(30, 30, 30);
  doc.text('Performance Summary', 20, y);
  y += 8;
  doc.setFontSize(10);
  const summaryLines = doc.splitTextToSize(report.performanceSummary || '', pageWidth - 40);
  doc.text(summaryLines, 20, y);
  y += summaryLines.length * 6 + 10;

  const addSection = (title, items) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text(title, 20, y);
    y += 8;
    doc.setFontSize(10);
    (items || []).forEach((item) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(`• ${item}`, 25, y);
      y += 6;
    });
    y += 8;
  };

  addSection('Strengths', report.strengths);
  addSection('Weaknesses', report.weaknesses);
  addSection('Suggestions', report.suggestions);
  addSection('Recommended Topics', report.recommendedTopics);
  addSection('Learning Path', report.learningPath);

  if (report.questionFeedback?.length) {
    if (y > 200) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(12);
    doc.text('Question-wise Feedback', 20, y);
    y += 10;
    report.questionFeedback.forEach((qf, i) => {
      if (y > 240) {
        doc.addPage();
        y = 20;
      }
      doc.setFontSize(10);
      doc.text(`Q${i + 1}: ${qf.question?.substring(0, 80)}...`, 20, y);
      y += 6;
      doc.text(`Score: ${qf.score}% | ${qf.feedback?.substring(0, 100)}`, 25, y);
      y += 10;
    });
  }

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by InterviewAce AI - Practice Smarter. Crack Interviews Faster.', 20, 285);

  doc.save(`InterviewAce_Report_${interview?.domain || 'Interview'}_${Date.now()}.pdf`);
};

export const formatDate = (date) =>
  new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });

export const getScoreColor = (score) => {
  if (score >= 80) return 'text-green-400';
  if (score >= 60) return 'text-yellow-400';
  return 'text-red-400';
};

export const getScoreBg = (score) => {
  if (score >= 80) return 'bg-green-400/20 border-green-400/30';
  if (score >= 60) return 'bg-yellow-400/20 border-yellow-400/30';
  return 'bg-red-400/20 border-red-400/30';
};
